### ISSUE TITLE
[RFC] Cloud-native OpenSearch

### ISSUE THREAD

**Issue by yupeng9** [opensearch-project/OpenSearch#17957]
### Is your feature request related to a problem? Please describe

Elasticsearch/OpenSearch, launched in 2010, was initially designed for on-premise deployments and smaller-scale applications, when cloud-computing was not prevailing at that time. This was shown in these observed design patterns:

 - **Bundled Roles:** Elasticsearch combined multiple roles (data storage, search, master node responsibilities) within a single node. This simplified setup and management for single-node or small clusters.
 - **Mesh Design for Metadata:** Cluster metadata was propagated to every node using a mesh design. This provided resilience against node failures as any node could provide the necessary information.
 - **Data Movement Algorithms:** Elasticsearch included algorithms to move data around the cluster. This was essential for rebalancing data in response to cluster growth, node additions, or node removals.

While this design initially provided convenience and ease of use, it has encountered significant challenges as cloud computing has become dominant and use cases have grown in scale and complexity:

 - **Reliability Challenges at Scale:** Managing very large Elasticsearch clusters (e.g., exceeding 200 nodes) becomes increasingly difficult. Data movement operations and cluster metadata replication can be time-consuming and lead to cluster pause.
 - **Rolling Restarts and Upgrades:** Performing rolling restarts or upgrades on large clusters can introduce latency spikes and potential data inconsistencies. Rollbacks can also be problematic. While [Blue/Green deployments](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-configuration-changes.html) offer a safer alternative, they require significant additional capacity, which can be costly.
 - **Challenges with Reactive Scaling:** Dynamically adding or removing replicas in response to changes in serving traffic is challenging. Additionally, imbalances in traffic across shards can lead to uneven replica distribution, impacting performance and resource utilization.
 - **Lack of Shard Distribution Control:** Managing shard distribution in large clusters is complex. Fine-tuning shard size and distribution can be crucial for optimizing performance, especially for latency-sensitive applications.
 
We propose transitioning OpenSearch to a cloud-native architecture. In the cloud era, the shift towards cloud computing and the demands of modern, large-scale applications necessitate a rethinking of OpenSearch's architecture. A cloud-native architecture, leveraging cloud services and adopting a shared-nothing design, can address many of these challenges:
 - **Cloud Components:** Utilizing cloud-based services for storage, compute, and networking can provide greater scalability, elasticity, and resilience.
 - **Shared-Nothing Architecture:** In a shared-nothing architecture, nodes operate independently and do not share resources. This can simplify cluster management, improve scalability, and reduce dependencies between nodes.

By embracing a cloud-native approach, OpenSearch can better meet the requirements of large-scale, cloud-based deployments. This transition can lead to improved operational efficiency, enhanced reliability, and greater scalability, enabling OpenSearch to handle the demands of modern data-intensive applications.

### Goal
Remove the 200-node limit on cluster size to enable high scalability.
Allow rolling upgrades and restarts with a 20% capacity buffer, eliminating the need for Blue/Green deployments.
Support rapid horizontal scaling per shard to provide elasticity.
Improve the reliability and reduce the operational work for large clusters
Allow shard size and distribution fine tuning for better query performance

### Architecture
The proposed architecture is shown as in Figure 1. And it includes several modular changes compared to the architecture today.

<img width="728" alt="Image" src="https://github.com/user-attachments/assets/419a7607-11c3-46f6-8492-9b7084d5b5f4" />

_Figure 1. Cloud-native OpenSearch architecture_
#### External Metadata Storage
An important architectural change that can be made is the decoupling of logical metadata and physical cluster state, and storing the metadata in a shared external storage system. This would result in better scalability and faster access. Currently, cluster state propagation to all nodes can be slow in large clusters.

This idea was also proposed in an [RFC](https://github.com/opensearch-project/OpenSearch/issues/17337) that lists faster index creation/updates, better memory efficiency, and faster crash recovery among the benefits of this change. An additional benefit to external metadata storage is that it can simplify control plane implementation and delegate durable metadata state management to an external system, such as etcd/zookeeper, which are known to be reliable, distributed coordination systems. The RFC recommends RocksDB for metadata storage; however, RocksDB is not a distributed system and therefore does not provide the high availability and durability of strongly consistent KV storage systems such as etcd/zookeeper. Many technologies, including Kubernetes and Apache Kafka/Pinot/HDFS/Yarn, utilize etcd and zookeeper for metadata storage and coordination. As the Hadoop ecosystem is being replaced by more modern, cloud-native, and real-time data tools, it is proposed that etcd be the default external metadata storage compared to zookeeper. The metadata storage layer can be abstracted to allow for other storage options, such as zookeeper.

Additionally, etcd provides features such as [watchers](https://etcd.io/docs/v3.5/dev-guide/interacting_v3/) that are valuable for nodes in building reactive, event-driven features, including leader election, service discovery, and dynamic configuration.

#### Shared-nothing Data Nodes
Another important architecture change to enable cloud-native design is to make the data nodes shared-nothing. This means that each data node is independent and does not need to communicate with other data nodes.  As shown in Figure 1, this is possible by the following changes:

 - Use segment-replication instead of the document-replication, so that the index segment is fetched from the remote storage (e.g. S3) 
 - Use the external metadata storage as described above as the logical data and its goal state, so that a newly data node knows which index and shards that it serves along with other configurations. Unlike today’s design, the data node needs to fetch only the metadata relevant to it but not the global metadata. Also, the data node does not need to communicate with the master node to collect the cluster state.
 - Use a dedicated coordinator for serving the queries, so that the data node does not need to maintain the global cluster state for routing and forwarding the queries to other data nodes like today’s design
 - A pull-based ingestion (introduced in this [RFC](https://github.com/opensearch-project/OpenSearch/issues/16495)) can further enhance the shared-nothing design as it removes the need of translog, so a data node can quickly recover by replaying the messages from the streaming source. In fact, with the pull-based ingestion, we can even enable the leaderless (or primary-less) design because all the shard replicas are equivalent to the primary in terms of data ingestion capability. 

This shared-nothing design brings in many benefits:
 - **Horizontal scalability**, the data nodes can be scaled out linearly and quickly without any shared bottlenecks. This is valuable for auto-scaling based on the traffic pattern.
 - **Reduced contention**, since the cluster state is not shared among data nodes, there is no waiting on its propagation
 - **Better fault isolation.** Since a data node does not depend on others,  one data node crashing does not affect the other nodes, which improves the cluster resilience.
 - **Easier operation.** Since the data nodes become more modular, they are easier to operate and maintain. We can add/remove data nodes similar to microservices, and perform rolling restart/upgrade without the 2X capacity needed for Blue/Green deployment.
 
#### Controller with Goal State vs Actual State Convergence Model
With the metadata stored in an external storage system, we could simplify the master node design to adopt the goal state vs actual state convergence model, a design pattern proven to be resilient in large scale distributed systems with real-world examples like Kubernetes. A system that naturally drifts toward correctness, can provide strong self-healing capabilities and thus ease the operation and maintenance.

With the metadata stored in the external storage, the Controller can also store the goal state of the data nodes, such as the index and shard to serve for a given data node. The data node also writes its actual node state in the external storage such as the node health, configurations of the index it is serving. The controller can watch and compare the goal state and actual state, and update the goal state when needed, such as the leader selection of a shard to a given data node. 

#### Stateless Coordinator
With the external metadata storage, it’s possible to make the coordinator a stateless service, so that it does not need to join the cluster like the data nodes . It can watch the metadata store and therefore it does not need to receive the cluster state from the master node. The cluster state includes the actual state of data nodes such as the shard allocation and node health, which can be used for building the routing table for the coordinator to dispatch the queries. A stateless coordinator can greatly simplify the deployment/operation, and it allows linear scalability of the coordinator horizontally.

### Related component

Cluster Manager

### Additional context

This RFC is also written in this [google doc](https://docs.google.com/document/d/1pe5Ew8LtopmOhRxWSIdCr_rxlTlHwwbeJFLmZQ8EFyY/edit?tab=t.0) for comments and discussion

**Comment by guojialiang92** [comment]
Hi, @yupeng9, I think it's a great idea and would like to discuss it.

> External Metadata Storage
> An important architectural change that can be made is the decoupling of logical metadata and physical cluster state, and storing the metadata in a shared external storage system. This would result in better scalability and faster access. Currently, cluster state propagation to all nodes can be slow in large clusters.

Will data nodes frequently access external Metadata storage (etcd/zookeeper) under the Cloud-Native architecture? Compared to the current Metadata stored locally on the node, I am concerned that frequent access to external metadata through the network will have a performance impact. (Compared to k8s, online search engines may face more metadata updates?)

**Comment by yupeng9** [comment]
> Hi, [@yupeng9](https://github.com/yupeng9), I think it's a great idea and would like to discuss it.
> 
> > External Metadata Storage
> > An important architectural change that can be made is the decoupling of logical metadata and physical cluster state, and storing the metadata in a shared external storage system. This would result in better scalability and faster access. Currently, cluster state propagation to all nodes can be slow in large clusters.
> 
> Will data nodes frequently access external Metadata storage (etcd/zookeeper) under the Cloud-Native architecture? Compared to the current Metadata stored locally on the node, I am concerned that frequent access to external metadata through the network will have a performance impact. (Compared to k8s, online search engines may face more metadata updates?)

This is a good question. Usually etcd allows thousands of clients to connect with 3k+ ops/sec for write and 20k+ ops/sec for read based on its use in kubernetes stack. This shall be sufficient to support a cluster of thousands of nodes based on the known industry use. Also, each data nodes can also cache metadata locally so that we can reduce the frequency of access and leverage watchers to be notified when changes are made. I'm also curious about kind of frequent metadata updates that you have in mind?

**Comment by navneet1v** [comment]
@yupeng9 Thanks for creating the proposal. If I am not wrong there has been several attempts being done in past to build a cloud native arch for OpenSearch(Ref: https://github.com/opensearch-project/OpenSearch/issues/13274 and another one you mentioned in your proposal, there can be more which I might be missing). This is a good proposal, but I want to understand what aer your thoughts on some of the core challenges for such arch:
1. The current metadata/cluster state being stored in OpenSearch is stored as 1 big blob in RAM of master nodes, does this new arch solves that problem? Because I think its pretty critical for scaling for large number of nodes.

In the proposal I see readers and writers of a shard on same node? So with this proposal we are not solving the reader/writer separation and shard placement problem? 

The etcd where cluster state is getting stored will that be the only implementation? or we will keep it open for extension?

**Comment by yupeng9** [comment]
> 
> 1. The current metadata/cluster state being stored in OpenSearch is stored as 1 big blob in RAM of master nodes, does this new arch solves that problem? Because I think its pretty critical for scaling for large number of nodes.

Agreed. The separation metadata and cluster state is part of this, and we will work on a spec to list the state and also how we can separate them. so that we can have a more finer-granular control which piece of metadata needs to be stored/fetched.
> 
> In the proposal I see readers and writers of a shard on same node? So with this proposal we are not solving the reader/writer separation and shard placement problem?

Reader/Writer separation is an ongoing effort, so it's orthogonal to this effort, though reader/writer separation is a good pattern for cloud-native architecture.

> 
> `etcd` where cluster state is getting stored will that be the only implementation? or we will keep it open for extension?
> 

It will be an API, and etcd-based implementation will be one plugin and the likely one that we'll build the prototype with.

> > This is a good question. Usually etcd allows thousands of clients to connect with 3k+ ops/sec for write and 20k+ ops/sec for read based on its use in kubernetes stack. This shall be sufficient to support a cluster of thousands of nodes based on the known industry use.
> 
> This ops/sec would be at a specific size of the response. With > 200 nodes and say thousands of indices with large index mappings, will we get same ops/sec?

Right, this ties to the first question. If we always store a gigantic blob cluster state, then the throughput will be limited. But if we can store things in finer granular, and update the key of the changed metadata only, I believe we can improve the throughput. wdyt?

**Comment by navneet1v** [comment]
Hi @yupeng9 thanks for providing the response. Please find my response below:


> > 1. The current metadata/cluster state being stored in OpenSearch is stored as 1 big blob in RAM of master nodes, does this new arch solves that problem? Because I think its pretty critical for scaling for large number of nodes.
> 
> Agreed. The separation metadata and cluster state is part of this, and we will work on a spec to list the state and also how we can separate them. so that we can have a more finer-granular control which piece of metadata needs to be stored/fetched.

Super awesome. It will be good if we can mention this in proposal. 

> > In the proposal I see readers and writers of a shard on same node? So with this proposal we are not solving the reader/writer separation and shard placement problem?
> 
> Reader/Writer separation is an ongoing effort, so it's orthogonal to this effort, though reader/writer separation is a good pattern for cloud-native architecture.

agreed.

> > `etcd` where cluster state is getting stored will that be the only implementation? or we will keep it open for extension?
> 
> It will be an API, and etcd-based implementation will be one plugin and the likely one that we'll build the prototype with.

Make sense. Love the idea of plugin will look to see more details on this.

> > > This is a good question. Usually etcd allows thousands of clients to connect with 3k+ ops/sec for write and 20k+ ops/sec for read based on its use in kubernetes stack. This shall be sufficient to support a cluster of thousands of nodes based on the known industry use.
> > 
> > 
> > This ops/sec would be at a specific size of the response. With > 200 nodes and say thousands of indices with large index mappings, will we get same ops/sec?
> 
> Right, this ties to the first question. If we always store a gigantic blob cluster state, then the throughput will be limited. But if we can store things in finer granular, and update the key of the changed metadata only, I believe we can improve the throughput. wdyt?

If the metadata is split into smaller granular chunks then yes provided throughput should be achieved. Will be looking forward for the proposal on splitting the metadata into chunks.


I have more question/ask/thought and would like to know what you think about it:
with the proposal mentioned in this GH issue will be able to achieve say millions of indexes in a cluster? Because in my mind the problem was always with metadata and shard management. I think with this proposal it should be resolved. If we are not thinking about this, can we take this as requirement for the current proposal.

**Comment by guojialiang92** [comment]
> This is a good question. Usually etcd allows thousands of clients to connect with 3k+ ops/sec for write and 20k+ ops/sec for read based on its use in kubernetes stack. This shall be sufficient to support a cluster of thousands of nodes based on the known industry use. Also, each data nodes can also cache metadata locally so that we can reduce the frequency of access and leverage watchers to be notified when changes are made. I'm also curious about kind of frequent metadata updates that you have in mind?

Thanks, @yupeng9. The access frequency may depend on the **number of nodes**/**number of indices**/**mapping size**. In this architecture, we may no longer need to split more clusters for stability, so millions of indexes may be attractive to me.

I still have some questions I want to confirm with you: 
1. Is there still **any form of communication** between the master node and the data node? In my understanding, it is not necessary. Under the new architecture, only the master node needs to upload the target state to the external Metadata storage, and the data node subscribes to the target state to the Metadata storage and reports the actual state.
2. Splitting large pieces of metadata into finer grains is very helpful for the scalability of the cluster. Also, I don't think this job relies on external metadata storage. In other words, are these two jobs orthogonal?

**Comment by navneet1v** [comment]
> 2\. Splitting a big blob of metadata into finer grains is very helpful for the scalability of the cluster (Based on your discussion with [@navneet1v](https://github.com/navneet1v)). Also, I don't think this job relies on external metadata storage. In other words, are these two jobs orthogonal?

@guojialiang92 your thought is right splitting the metadata and external metadata storage is independent, but splitting metadata into smaller chunks actually makes the external metadata storage work simpler and scalable. This also ensures that clusters with large number of nodes can be created(>200 nodes), which was one of the main motivation for this proposal.

**Comment by yupeng9** [comment]
> 
> Thanks, [@yupeng9](https://github.com/yupeng9). The access frequency may depend on the **number of nodes**/**number of indices**/**mapping size**. In this architecture, we may no longer need to split more clusters for stability, so millions of indexes may be attractive to me.

Curious, millions of indexes is a lot, why do we need to support this much?
> 
> I still have some questions I want to confirm with you:
> 
> 1. Is there still **any form of communication** between the master node and the data node in the Cloud Native architecture? In my understanding, it is not necessary. Under the new architecture, only the master node needs to upload the target state to the external Metadata storage, and the data node subscribes to the target state to the Metadata storage and reports the actual state.

Yes, that's my feeling too that master node needs to update the goal state, and it does not need to handle the state propagation.

> 3. Splitting a big blob of metadata into finer grains is very helpful for the scalability of the cluster (Based on your discussion with [@navneet1v](https://github.com/navneet1v)). Also, I don't think this job relies on external metadata storage. In other words, are these two jobs orthogonal?

Yeah, these two can be independent, but when we design the content of the external metadata storage, we need a spec of the metadata layout.

**Comment by navneet1v** [comment]
> > Thanks, [@yupeng9](https://github.com/yupeng9). The access frequency may depend on the **number of nodes**/**number of indices**/**mapping size**. In this architecture, we may no longer need to split more clusters for stability, so millions of indexes may be attractive to me.
> 
> Curious, millions of indexes is a lot, why do we need to support this much?

@yupeng9 
I don't think so millions of indices is a lot. If you look at systems like Turbopuffer they support tens of millions of indices. https://turbopuffer.com/docs/limits . The main use case of millions of indices is multi-tenancy and tenant isolation. Idea is rather than creating 1 single giant index with all the tenants data and then searching using filters, you can create indices per tenant and then search based on that. This is very clean, easy to scale and maintain from a user side, provides awesome query latency. 

So I believe with this proposal we should be able to achieve millions of indices. I do agree we might need more work in other part of OpenSearch to make this work, but as per my deep-dive and understanding splitting metadata into smaller chunks is one of the requirement to support multiple indices, followed by not keeping shards on the node(writable warm).

**Comment by yupeng9** [comment]
> [@yupeng9](https://github.com/yupeng9) I don't think so millions of indices is a lot. If you look at systems like Turbopuffer they support tens of millions of indices. https://turbopuffer.com/docs/limits . The main use case of millions of indices is multi-tenancy and tenant isolation. Idea is rather than creating 1 single giant index with all the tenants data and then search using filters, user can create indices per tenant and then search based on that. This is very clean, easy to scale and maintain from a user side, provides awesome query latency.

Yes, I agree multi-tenancy makes sense but millions of indices is still a lot.. Would that mean tens of thousands of customers sharding the same opensearch cluster? I feel the data size and cluster size will first run into the limit before the number of indices

**Comment by msfroh** [comment]
Thanks, @yupeng9! This is a great idea.

I'm going to start documenting some of the APIs currently implicated in managing/applying cluster state to come up with a design that can cleanly abstract away the current cluster manager model.

**Comment by navneet1v** [comment]
> > [@yupeng9](https://github.com/yupeng9) I don't think so millions of indices is a lot. If you look at systems like Turbopuffer they support tens of millions of indices. https://turbopuffer.com/docs/limits . The main use case of millions of indices is multi-tenancy and tenant isolation. Idea is rather than creating 1 single giant index with all the tenants data and then search using filters, user can create indices per tenant and then search based on that. This is very clean, easy to scale and maintain from a user side, provides awesome query latency.
> 
> Yes, I agree multi-tenancy makes sense but millions of indices is still a lot.. Would that mean tens of thousands of customers sharding the same opensearch cluster? I feel the data size and cluster size will first run into the limit before the number of indices

I disagree on part where we will run out of cluster size. Because you can still create a cluster with  1 index with 10Billion docs and you can also have a 100K docs per index will give us atleast 100K indices. and now with more than 200 nodes we can go upto 100B and more.

**Comment by msfroh** [comment]
I have an update on progress on a PoC for this. I'm pushing my changes to https://github.com/msfroh/OpenSearch/tree/clusterless_datanode.

1. I made [a relatively small change](https://github.com/msfroh/OpenSearch/commit/64f09cf3107b7f652eb02189dbaa4934cede4b7a) to let nodes start up without joining a cluster. Essentially, I commented out anything related to `Discovery`. Obviously a real implementation would need to make this stuff conditional.
2. I have [another, bigger change](https://github.com/msfroh/OpenSearch/commit/663a25a9fb6d34bea376c0a84c03bfc0ee27d9bf) that adds an API to write cluster state to a node. I was able to push an index mapping to the node and initialize a shard. Transitioning the shard from "initializing" to "started" still fails, but that's probably my fault.

My thinking is that a controller can write cluster state to ETCD (or DynamoDB, Cassandra, etc). An agent running on data nodes (writers or readers) can watch for cluster state changes and publish filtered cluster state (with just the information the local node needs) to the local node. For a data node, that means only metadata for indices with shards hosted on the node, as well as a single node routing table for the current node. An agent running on coordinators will also publish cluster state, but it can exclude most index metadata (mappings, most settings). The coordinator needs a routing table with readers and their shards, so it knows how to fan out search requests.

I haven't decided if the agent should be part of the OpenSearch process. For my PoC, I'm playing the part of the agent using `curl`.

**Comment by yupeng9** [comment]
looks cool. thanks!

>An agent running on data nodes (writers or readers) can watch for cluster state changes and publish filtered cluster state (with just the information the local node needs) to the local node. 

In certain environments, it might not be easy to deploy an agent on a host. Can we have a module/plugin in OpenSearch that can watch for cluster state change and invoke the API to make this more self-contained? Also ETCD is a key-value store, so we can also organize the cluster state as key-value pairs, so that we do not need the filtering but directly watch the relevant keys.

**Comment by msfroh** [comment]
> In certain environments, it might not be easy to deploy an agent on a host. Can we have a module/plugin in OpenSearch that can watch for cluster state change and invoke the API to make this more self-contained?

Yes, anything we do out-of-process can be done in-process too. In fact, doing it in-process should make the code changes a lot smaller -- we don't need to deserialize an XContent representation of the cluster state.

> Also ETCD is a key-value store, so we can also organize the cluster state as key-value pairs, so that we do not need the filtering but directly watch the relevant keys.

Yes, that should be doable. In particular, I'm leaning toward the idea of the agent/plugin/per-node "thing" reading from the store and building the `ClusterState` object locally. That way, we're not forced to distribute OpenSearch's cluster state.

**Comment by shwetathareja** [comment]
Thanks @yupeng9 for starting the discussion.

Regarding the handling of cluster state in the cloud native architecture. There are multiple things to consider:
1. Storing the state to a remote store and each data node fetches the state from remote storage. [This already exists in OpenSearch](https://github.com/opensearch-project/OpenSearch/issues/9143). The backend storage is independent of the in-memory Cluster State data structure and in memory state is re-created using remote store objects. 
2. On-demand fetching of index metadata only for indices which are assigned to a particular data node. This is not implemented yet and discussed in Remote state RFC.
3. Breaking the cluster state in granular objects like index metadata, shard routing allocation, snapshots, plugins custom metadata, data streams, etc. This would benefit for parallel processing of state and also handling of state in more scalable fashion where it is not treated as single blob. This would require changing the ClusterStateExecutors. I am not sure if it is attempted here.
4. Refactoring the metadata management as a library which is not tied to in-memory cluster state object and can be plugged in easily for in-cluster cluster manager setup or in a cloud native distributed setup where it could be hosted as a multi tenant service as well.
5. Eventually making Cluster Manager Stateless where any node or system can process the updates to cluster state by directly interacting with remote store as long as the remote store provides conditional writes semantics to ensure strong consistency. This would provide the infinite scale and not bound by limits of single cluster manager node.

@msfroh I have not looked at your code yet. Are you just looking to move cluster state store interaction to a plugin?

**Comment by yupeng9** [comment]
Thanks for sharing the thoughts! I agree with these things to consider. 

> Thanks [@yupeng9](https://github.com/yupeng9) for starting the discussion.
> 
> Regarding the handling of cluster state in the cloud native architecture. There are multiple things to consider:
> 
> 1. Storing the state to a remote store and each data node fetches the state from remote storage. [This already exists in OpenSearch](https://github.com/opensearch-project/OpenSearch/issues/9143). The backend storage is independent of the in-memory Cluster State data structure and in memory state is re-created using remote store objects. Metadata storage has its own versioning. Today, CM informs the data nodes that new state is available in remote store via publication (push) but you can build your watcher/ poller on the remote storage directly as well in the plugin (lets say).
> 2. On-demand fetching of index metadata only for indices which are assigned to a particular data node. This is not implemented yet and discussed in Remote state RFC.

> 4. Breaking the cluster state in granular objects like index metadata, shard routing allocation, snapshots, plugins custom metadata, data streams, etc. This would benefit for parallel processing of state and also handling of state in more scalable fashion where it is not treated as single blob. This would require changing the ClusterStateExecutors. I am not sure if it is attempted here.

Yes, with this, we can store the granular objects as k/v pairs in etcd, so that we can watch their changes to be more efficient in state change reaction

> 6. Refactoring the metadata management as a library which is not tied to in-memory cluster state object and can be plugged in easily for in-cluster cluster manager setup or in a cloud native distributed setup where it could be hosted as a multi tenant service as well.
> 7. Eventually making Cluster Manager Stateless where any node or system can process the updates to cluster state by directly interacting with remote store as long as the remote store provides conditional writes semantics to ensure strong consistency. This would provide the infinite scale and not bound by limits of single cluster manager node.
> 8. Make metadata and shard routing management agnostic of the OpenSearch version and plugin versions so that we don't end maintaining large no. of versions when hosting it in multi tenant fashion> > [@msfroh](https://github.com/msfroh) I have not looked at your code yet. Are you just looking to move cluster state store interaction to a plugin?

**Comment by msfroh** [comment]
> @msfroh I have not looked at your code yet. Are you just looking to move cluster state store interaction to a plugin?

@shwetathareja, I was essentially planning to do the 6 things outlined in your comment. So far, I've confirmed that a data node can work based on some "synthetic" cluster state without actually being part of a cluster.

**Comment by shwetathareja** [comment]
@rajiv-kv has also started looking into Stateless Cluster Manager and as the first step he is looking into refactoring metadata lib. @rajiv-kv to share more details. I think we should collaborate here so that we are not spending duplicate effort here.

**Comment by rajiv-kv** [comment]
Thanks @yupeng9 for a detailed proposal. I like the idea of providing extension points in cluster manager for leveraging cloud infrastructure.

I had few follow-up questions.

1. With poll based metadata propagation, it is being suggested that eventual consistent (or even inconsistent) view of metadata is acceptable. However the existing design strives for strong consistency of metadata across nodes in cluster. Do you think this deviates from fundamental tenets of OpenSearch and there might be more components (other than cluster manager) that could potentially be impacted because this assumption does not hold true ?
2. What are you thoughts around multi-tenancy of cluster manager for metadata management ? With on-premise, every customer gets own deployment, which will not be true in cloud. A single deployment of cluster manager might have to manage the metadata for multiple tenants.
3. Index Stats is another information where nodes broadcast over transport to retrieve information from the individual nodes of cluster. Do you see the coordinator nodes also hosting admin endpoints of OpenSearch ? If so, we need to consider mechanisms for retrieval of metadata stats in cloud along with metadata.
4. Some of the goals listed in RFC (200 node, reliability, large cluster state) have been addressed in [Remote Publication](https://github.com/opensearch-project/OpenSearch/issues/9143), [Async Shard Fetch](https://github.com/opensearch-project/OpenSearch/issues/8098) and improvements of cluster manager in 2.17. Do you still see them as concerns ?


@msfroh - As part of [state](https://github.com/opensearch-project/OpenSearch/issues/9337) and [routing](https://github.com/opensearch-project/OpenSearch/issues/14164) persistence, there are interfaces exposed in cluster manager that could be leveraged for external metadata storage. Please take a look at `PersistedState` and its S3 implementation `RemotePersistedState` for details. Likewise, datanodes can download the state directly from remote with the entry point into `RemoteClusterStateService`. You could refer to this [15424](https://github.com/opensearch-project/OpenSearch/pull/15424) where admin APIs leverage persisted state from remote. I believe these interfaces can be extended to persist & retrieve state to etcd as well. Please take a look and let me know your thoughts on extending these interfaces for etcd based persistence.

As part of stateless cluster manager, I was thinking to initially focus on separating out persistence of index metadata from cluster state. This is more in lines with an existing proposal here [13197](https://github.com/opensearch-project/OpenSearch/issues/13197) to extract metadata-commons as library and use it across server module and cloud native implementations. 
Subsequently as next step, we could introduce interfaces around cluster state management and shard management to abstract out the existing implementation of task-queue and reroute in core. For cloud native , the interfaces could be implemented outside the core, where the coordination can be achieved by interacting with remote service(s). 
Currently these are in prototype phase and I will follow-up with a proposal on these two areas to get thoughts from the community.

**Comment by yupeng9** [comment]
> Thanks [@yupeng9](https://github.com/yupeng9) for a detailed proposal. I like the idea of providing extension points in cluster manager for leveraging cloud infrastructure.
> 
> I had few follow-up questions.
> 
> 1. With poll based metadata propagation, it is being suggested that eventual consistent (or even inconsistent) view of metadata is acceptable. However the existing design strives for strong consistency of metadata across nodes in cluster. Do you think this deviates from fundamental tenets of OpenSearch and there might be more components (other than cluster manager) that could potentially be impacted because this assumption does not hold true ?

I want to better understand the consistency here. As the cluster manager talks to each node individually, the cluster state will be eventually consistent across the nodes, right?

> 3. What are you thoughts around multi-tenancy of cluster manager for metadata management ? With on-premise, every customer gets own deployment, which will not be true in cloud. A single deployment of cluster manager might have to manage the metadata for multiple tenants.

I feel this is an orthogonal problem, as the metadata storage decoupling does not mean the cluster manager cannot manage the metadata for multiple tenants. However, the external metadata storage provides more flexibility of how this metadata is generated, and thus more plugins than the existing cluster manager for the control plane.

> 5. Index Stats is another information where nodes broadcast over transport to retrieve information from the individual nodes of cluster. Do you see the coordinator nodes also hosting admin endpoints of OpenSearch ? If so, we need to consider mechanisms for retrieval of metadata stats in cloud along with metadata.

This is a good question, and it depends on how we position the coordinator nodes. I feel coordinators are mainly used by the data plane, i.e. read/write traffic. So it may not need the admin endpoints.

> 7. Some of the goals listed in RFC (200 node, reliability, large cluster state) have been addressed in [Remote Publication](https://github.com/opensearch-project/OpenSearch/issues/9143), [Async Shard Fetch](https://github.com/opensearch-project/OpenSearch/issues/8098) and improvements of cluster manager in 2.17. Do you still see them as concerns ?

Thanks for sharing those RFCs and it's good to see those improvements. We have not adopted those features yet, but we shall give it a try. This 200 node constraint stems both from our operational experience (e.g. large metadata slowing down the cluster) and the information we gathered from other companies

**Comment by msfroh** [comment]
I've made more progress on my prototype (everything is pushed to [my branch](https://github.com/msfroh/OpenSearch/tree/clusterless_datanode)).

The workflow is now as folllows:

1. You can push index metadata for each index independently to etcd, using the index name as a key and the JSON metadata as the value.
2. For a data node, you can assign shards by writing a node config value to a key corresponding to the node ID. (In practice node IDs are probably not the best choice, but it works well for my prototype.) The node config value looks like `{"local_shards":{"myindex":{"0":"PRIMARY", "1": "REPLICA" }, "some_other_index": { "0" : "SEARCH_REPLICA" } }}`.
3. For a coordinator node, you don't need to provide any **any** index metadata. You just need to point from index names to the per-shard routing.

**Comment by navneet1v** [comment]
> > [@yupeng9](https://github.com/yupeng9) I don't think so millions of indices is a lot. If you look at systems like Turbopuffer they support tens of millions of indices. https://turbopuffer.com/docs/limits . The main use case of millions of indices is multi-tenancy and tenant isolation. Idea is rather than creating 1 single giant index with all the tenants data and then search using filters, user can create indices per tenant and then search based on that. This is very clean, easy to scale and maintain from a user side, provides awesome query latency.
> 
> Yes, I agree multi-tenancy makes sense but millions of indices is still a lot.. Would that mean tens of thousands of customers sharding the same opensearch cluster? I feel the data size and cluster size will first run into the limit before the number of indices

@yupeng9 Multi-tenancy is one use case, but I thought of other places too where millions of indices will be very helpful. Example:

So as a user of OpenSearch operating a hyper local business where I want to index information at zip-code/city level per index rather than doing in a single giant index and then using filters to do the search. So the solution becomes very promising because 
1. Now I can scale indices individually rather than scaling everything at once.
2. Snapshots, merges, recovery, blast radius become very low as every index is encapsulated separately. 

Let me know what you think on this.

**Comment by msfroh** [comment]
@navneet1v -- In theory, it would be possible to handle the kind of scale you're describing with this kind of solution. If each index has metadata stored in the central store (etcd, Cassandra, DynamoDB, etc), it becomes very easy to allocate shards "on-demand".

When an indexing or search request comes in, if the shard(s) to which the request would be routed are not currently assigned to any nodes, we could assign them, process the request, then unassign them (or treat it like an LRU cache, where they get evicted when the capacity is needed for something else). It's easy on the read side -- the write path is trickier because we need to make sure that two nodes aren't trying to write to the same shard.

**Comment by navneet1v** [comment]
@msfroh Exactly my point and I tried to ask the same here: https://github.com/opensearch-project/OpenSearch/issues/17957#issuecomment-2817783634 

I think this change is in the right direction. But my question is do you guys thinking around this kind of scale as a testing criteria for this feature?

**Comment by msfroh** [comment]
> Sorry I might have missed out on some threads, but I would like to understand what properties wouldn't be satisfied through the blob store based persistence layer

There's a much bigger problem to solve, where cluster state is a large, unwieldy mass, where every node receives the full cluster state, which contains a bunch of stuff that most nodes don't need.

While I realize that my branch has hundreds of lines of code and may be unwieldy to read through, [this class](https://github.com/msfroh/OpenSearch/blob/clusterless_datanode/plugins/cluster-etcd/src/main/java/org/opensearch/cluster/etcd/ETCDStateDeserializer.java) shows how we can propagate specific information to nodes that need it. Data nodes get index metadata only for the indices for which they host shards and know about no other nodes in the cluster. Coordinator nodes get enough information to route requests to data nodes, and nothing more.

My branch is in a "done for now" state, while I work on creating an initial implementation of the Controller, which can live outside of OpenSearch and won't share any code with it. If anyone wants to try out my branch, I'm happy to write up a quickstart guide for running etcd locally and using that to control a node's behavior.

**Comment by shwetathareja** [comment]
@msfroh The remote cluster state implementation takes care of storing each IndexMetadata as separate object and all the [IndexMetadata](https://github.com/opensearch-project/OpenSearch/blob/4d6f8bafe489bde867b783c6facd189657ec34e6/server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java#L35) are tracked by [ClusterMetadataManifest ](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java)file in remote. Today, the download logic downloads the full or differential cluster state [here](https://github.com/opensearch-project/OpenSearch/blob/4d6f8bafe489bde867b783c6facd189657ec34e6/server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java#L269). This can easily be updated to consider downloading only index metadata for shards assigned to that node. This is how we are planning to implement (in the OpenSearch core) lazy download of index metadata on the data nodes for the shards assigned to that node. ETCD can be added as another remote implementation (similar to S3) in the plugin as needed. We may need to make certain remote store interfaces for cluster state public which are marked internal. You can look at [RemoteIndexMetadataManager](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java) for sample remote store interaction for read/ write.

**Comment by msfroh** [comment]
>  This can easily be updated to consider downloading only index metadata for shards assigned to that node. 

Thanks, @shwetathareja! 

I'm going to keep moving forward with my implementation for now, since it starts from the (IMO much more interesting) premise of "What if we could run OpenSearch without a *cluster*?" That's the fundamental mistake that was made 15 years ago -- the cluster model just doesn't scale. So, instead of slowly rolling out a series of patches to try to make the broken cluster model a little less painful, I'm going start from the point of not having a cluster at all. (As I said, my branch already does this, with 4 weeks of part-time effort by one person. See the [README](https://github.com/msfroh/OpenSearch/blob/clusterless_datanode/README.md) that I wrote to see what's possible so far.)

Over time, we can probably share components back and forth between the implementations. I don't believe we're trying to solve the same problem -- or if we are, we're taking radically different approaches and I believe that my approach is the correct one.

**Comment by shwetathareja** [comment]
>I don't believe we're trying to solve the same problem -- or if we are, we're taking radically different approaches and I believe that my approach is the correct one.

I think we are trying to solve the same problem where metadata CRUD lifecycle and state processing is moved out of the cluster completely. The data and coordinator nodes fetches the required metadata on demand from a different storage. Yes definitely, everyone has the freedom to experiment with their implementation and innovate. But, I think its early to conclude which is correct and would require more broader discussion to conclude the same.

**Comment by msfroh** [comment]
I reworked the first commit from my PoC branch plus a small change to shard recovery that I had to make later, so that I could open a PR with the extent of the changes I've had to make to core to get my PoC working: https://github.com/opensearch-project/OpenSearch/pull/18479

Everything else goes in a plugin, so the impact to core is pretty minimal, which IMO is pretty nice.

**Comment by msfroh** [comment]
@bryanlb -- I just noticed that @yupeng9's diagram in this issue is (coincidentally) very similar to the Astra architecture diagram at https://slackhq.github.io/astra/architecture.html#system-overview. 

Hopefully, with these changes, along with pull-based indexing, OpenSearch will be able to support a similar model to Astra. I might try spinning up an Astra cluster manager and ZooKeeper as a possible implementation of the controller + cluster state to prove out my PoC.

**Comment by adityam0120** [comment]
@msfroh @yupeng9 Just for reference, Milvus(which is arguably the most popular open source vector database right now), uses etcd for key-value based metadata engine that accesses and stores metadata of its internal components, including proxies, index nodes, and more. The architecture you are trying to achieve is similar to theirs. Adding links in case it helps to learn from their implementation

https://github.com/milvus-io/milvus/tree/master/internal/kv/etcd 

https://milvus.io/docs/four_layers.md

**Comment by guojialiang92** [comment]
The above discussion is very exciting! We are also exploring ways to expand the metadata management capabilities of clusters in multi-tenant scenarios. 
Meanwhile, I'm glad to see that the community has already made some efforts. There are the following issues that I would like to discuss further. @rajiv-kv @shwetathareja 

> Some of the goals listed in RFC (200 node, reliability, large cluster state) have been addressed in [Remote Cluster State](https://github.com/opensearch-project/OpenSearch/issues/9143), [Async Shard Fetch](https://github.com/opensearch-project/OpenSearch/issues/8098) and improvements of cluster manager in 2.17. Do you still see them as concerns ?

1. I would like to know if there are currently any production practices with [Remote Cluster State](https://github.com/opensearch-project/OpenSearch/issues/9143) and [Async Shard Fetch](https://github.com/opensearch-project/OpenSearch/issues/8098) enabled, and what is the maximum number of nodes/indices/shards that can be supported at present? 

> @msfroh The remote cluster state implementation takes care of storing each IndexMetadata as separate object and all the [IndexMetadata](https://github.com/opensearch-project/OpenSearch/blob/4d6f8bafe489bde867b783c6facd189657ec34e6/server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java#L35) are tracked by [ClusterMetadataManifest ](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java)file in remote. Today, the download logic downloads the full or differential cluster state [here](https://github.com/opensearch-project/OpenSearch/blob/4d6f8bafe489bde867b783c6facd189657ec34e6/server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java#L269). This can easily be updated to consider downloading only index metadata for shards assigned to that node. This is how we are planning to implement (in the OpenSearch core) lazy download of index metadata on the data nodes for the shards assigned to that node. ETCD can be added as another remote implementation (similar to S3) in the plugin as needed. We may need to make certain remote store interfaces for cluster state public which are marked internal. You can look at [RemoteIndexMetadataManager](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java) for sample remote store interaction for read/ write.

2. Assuming the issue of oversized metadata has been resolved, will there still be other bottlenecks?
3. Assuming there are 100 million tenants, with each tenant having 1 index (1 shard per index), can it handle the load?

**Comment by shwetathareja** [comment]
>I would like to know if there are currently any production practices with https://github.com/opensearch-project/OpenSearch/issues/9143 and https://github.com/opensearch-project/OpenSearch/issues/8098 enabled, and what is the maximum number of nodes/indices/shards that can be supported at present?

It has been tested with 500k shards and 1000 nodes with remote state changes and Batch Async fetch. There are few tunings pending for state download threadpool to handle download of large no. of indices. Also, there is plan to decouple primary term and in sync allocation id which is stored in IndexMetadata and keep it with Index level RoutingTable, this will prevent unnecessary upload/ download of IndexMetadata due to shard assignment changes when there are node drops or shard movements.

> Assuming there are 100 million tenants, with each tenant having 1 index (1 shard per index), can it handle the load?

From the cluster state handling perspective, few things which are pending (which we were discussing earlier):
1. Lazy download of IndexMetadata only for indices assigned to that node
2. Decouple of the primary term and insync allocations from IndexMetadata and move it with RoutingTable 
4. Eventually getting rid of local election and moving toward Stateless Cluster Manager.
5. Also, we wanted to explore instead of keeping one file per index to maintaining a different storage schema and then block level fetch to optimize on read/write operations on remote storage.

**Comment by shwetathareja** [comment]
> Meanwhile, I'm glad to see that the community has already made some efforts. There are the following issues that I would like to discuss further. @rajiv-kv @shwetathareja 

@guojialiang92 yes, would love to have more discussion on multi tenancy and scaling of CM.

**Comment by muralikpbhat** [comment]
Really good proposal and good discussion in this RFC. I agree that external metadata store and granular metadata propagation is really good and there are parallel efforts in remote state and in this github issue, which is creating some friction. While both might achieve the same thing eventually, I understand there are significant differences in the approach and we should ensure we design it such a way that they don't conflict and reuse wherever possible. 

The approach of state with watchers and the nodes listening to that is a good direction. If we can ensure that the watchers in each node is abstracted in a way that it works with existing remote state also, we might be achieving best of both worlds. As one can imagine, new dependencies like etcd, dynamo or whatever may not be an easy shift for every OpenSearch installations, especially if someone has thousands of clusters. If someone is using remote state with cluster based implementation, allowing them to continue with that even in the new cloud native design will be a win-win situation.

I envision 2 things to ensure remote state based approach still continues to work: 1) Ensure we design the watchers such a way that it can also pull granular information from S3(remote store) which is already broken into smaller objects per index. Just model S3 also as another store like etcd. 2) If there are implementations of the metadata which doesn't support notifications/change listener and still prefer cluster manager instead of new dependencies, continue to have the cluster manager notify these data-node agents when there is a change.

**Comment by andrross** [comment]
> While both might achieve the same thing eventually, I understand there are significant differences in the approach and we should ensure we design it such a way that they don't conflict and reuse wherever possible.

To summarize my understanding of the two approaches:

- Clusterless data nodes: This has been enabled by [PR #18479](#18479). It allows data nodes to start without joining a cluster. A plugin like [cluster-etcd](https://github.com/opensearch-project/cluster-etcd) must be installed that can fetch the relevant metadata and construct a cluster state to allow the data node to function. This has some good properties that data nodes are very independent. It also comes with the caveat that pretty much all of the admin and cluster management APIs and business logic in OpenSearch are no longer functional. In the case of cluster-etcd, all the business logic for creating and modifying the index metadata and shard routing data that is stored in etcd must be implemented by something else (i.e. a separate control plane).
- [Stateless cluster manager](https://github.com/opensearch-project/OpenSearch/issues/19202): This effort will offload the storage, durability, consistency, and propagation of cluster state to external services as opposed to the current model where all of this implemented directly in the cluster manager nodes themselves. The business logic for managing this state (i.e. all the admin and cluster management APIs) will stay within OpenSearch, but will be much lighter weight since much of the complexity (consistency, durability, etc) is offloaded to a cloud service.

To echo @muralikpbhat's point, I think these efforts can continue in parallel without conflicting. The clusterless model ends up being not very intrusive to OpenSearch itself, since it simply allows nodes to act as "dumb" data nodes and leaves control plane functionality as an exercise for the reader to implement externally. The stateless cluster manager will require more changes to OpenSearch, but will also be much more of a drop-in replacement for existing clusters, just without major scaling and operational pain points related to the leader-elected cluster manager.

@msfroh @rajiv-kv @shwetathareja Please correct me if I'm wrong about any of this.
