### ISSUE TITLE
[BUG] RemoteStoreIT.testRemoteTranslogRestore flaky test failure

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6188]
The following failed with a timeout, but is not reproducible:

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.remotestore.RemoteStoreIT.testRemoteTranslogRestore" -Dtests.seed=DF38037B9405A5AE -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=de-CH -Dtests.timezone=America/North_Dakota/Beulah -Druntime.java=17

org.opensearch.remotestore.RemoteStoreIT > testRemoteTranslogRestore FAILED
    java.lang.AssertionError: timed out waiting for yellow state
        at __randomizedtesting.SeedInfo.seed([DF38037B9405A5AE:C4871B4D04A1356B]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1007)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureYellowAndNoInitializingShards(OpenSearchIntegTestCase.java:960)
        at org.opensearch.remotestore.RemoteStoreIT.verifyRestoredData(RemoteStoreIT.java:143)
        at org.opensearch.remotestore.RemoteStoreIT.testRemoteTranslogRestore(RemoteStoreIT.java:181)
```

(#6182) https://build.ci.opensearch.org/job/gradle-check/10624/consoleFull

/cc @sachinpkale

**Comment by sachinpkale** [comment]
Thanks @andrross , I will take a look and fix.

**Comment by sachinpkale** [comment]
The changes in https://github.com/opensearch-project/OpenSearch/pull/5854 should fix this flakiness of the test, will check further.

**Comment by sachinpkale** [comment]
The [backport](https://github.com/opensearch-project/OpenSearch/pull/6170) of https://github.com/opensearch-project/OpenSearch/pull/6086 is still in flight. Once the changes are backported, this test should not fail.

**Comment by ashking94** [comment]
PR build is in progress for the backport PR. #6170 - we can merge it once the build is successful.

**Comment by ashking94** [comment]
The above PR has been merged. Closing it.

**Comment by reta** [comment]
Still happening on `2.x`: 

```
Failed
org.opensearch.remotestore.RemoteStoreIT.testRemoteTranslogRestore

java.lang.AssertionError: timed out waiting for yellow state
	at __randomizedtesting.SeedInfo.seed([7E138B60D5A3FE42:65AC935645076E87]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1007)
	at org.opensearch.test.OpenSearchIntegTestCase.ensureYellowAndNoInitializingShards(OpenSearchIntegTestCase.java:960)
	at org.opensearch.remotestore.RemoteStoreIT.verifyRestoredData(RemoteStoreIT.java:143)
```

[1] https://build.ci.opensearch.org/job/gradle-check/10805/

**Comment by sachinpkale** [comment]
Let me mute the test until we fix it completely.

**Comment by sachinpkale** [comment]
Muted the test as part of https://github.com/opensearch-project/OpenSearch/pull/6230

**Comment by sachinpkale** [comment]
Currently muted, will be fixed in 2.7.0

**Comment by DarshitChanpura** [comment]
Hey @andrross @sachinpkale . Is the issue still on-track for being completed by code-freeze (Apr 17) for `v2.7.0`?

**Comment by DarshitChanpura** [comment]
Closing as this one looks like it was fixed via bunch of PRs: #6252 and then via #6375 and both of these have been backported to `2.x` line (#6265 & #6378)
