### ISSUE TITLE
[BUG] [Build Break] buildBwcLinuxTar is expecting 2.7.0 artifact but getting 2.7.1

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#7396]
**Describe the bug**
The gradle task`:distribution:bwc:staged:buildBwcLinuxTar` fails on the Jenkins build and locally.  See the error message

```
> Task :distribution:bwc:staged:checkoutBwcBranch
Performing checkout of opensearch-project/2.7...
Checkout hash for :distribution:bwc:staged is f28d1898ee227461c438f054a02e7701a3564393
```
...
```
* What went wrong:
Execution failed for task ':distribution:bwc:staged:buildBwcLinuxTar'.
> Building 2.7.0 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/staged/build/bwc/checkout-2.7/distribution/archives/linux-tar/build/distributions/opensearch-min-2.7.0-SNAPSHOT-linux-x64.tar.gz
```

**To Reproduce**
Run `./gradlew :distribution:bwc:staged:buildBwcLinuxTar`

**Additional context**
- Impacts PR https://github.com/opensearch-project/OpenSearch/pull/7374

**Comment by peternied** [comment]
I've added the flaky test flag because it seems like this test is not reliable due to changes unrelated to the current pull request.

**Comment by kotwanikunal** [comment]
@peternied This was fixed as a part of #7379 
Can you please try and rebase your branch?

**Comment by kotwanikunal** [comment]
@peternied Can you please verify the fix and close out the issue?

**Comment by peternied** [comment]
I've created #7398 that fixes the cause of this flaky test.  After that pull request is merged / closed, I'll resolve this issue.

**Comment by peternied** [comment]
Impacted [PR](https://github.com/opensearch-project/OpenSearch/pull/11378), jenkins gradle check [logs](https://build.ci.opensearch.org/job/gradle-check/30962/console).

**Comment by peternied** [comment]
@andrross While #11926 did reference this issue it didn't fix the underlying problem - if a new version is published existing pull requests have to rebase/merge or they will fail.  Was there another PR or test change that addressed this?

- https://github.com/opensearch-project/OpenSearch/pull/11926#discussion_r1457863807

**Comment by andrross** [comment]
> if a new version is published existing pull requests have to rebase/merge or they will fail. Was there another PR or test change that addressed this?

No, that behavior is still present.
